CREATE TABLE `cold_client_installations` (
	`app_id` integer PRIMARY KEY NOT NULL,
	`loader_architecture` text NOT NULL,
	`executable_relative_path` text NOT NULL,
	`steam_api_relative_path` text,
	`launch_arguments` text NOT NULL,
	`launch_argument_source` text,
	`gbe_asset_id` integer NOT NULL,
	`gse_asset_id` integer NOT NULL,
	`generated_depot_fingerprint` text NOT NULL,
	`managed_core_files` text NOT NULL,
	`configured_at` integer NOT NULL,
	FOREIGN KEY (`app_id`) REFERENCES `library`(`app_id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "cold_client_installations_app_id_valid" CHECK("cold_client_installations"."app_id" > 0 AND "cold_client_installations"."app_id" <= 4294967295),
	CONSTRAINT "cold_client_installations_loader_architecture_valid" CHECK("cold_client_installations"."loader_architecture" IN ('x86', 'x64')),
	CONSTRAINT "cold_client_installations_executable_path_valid" CHECK("cold_client_installations"."executable_relative_path" <> ''),
	CONSTRAINT "cold_client_installations_steam_api_path_valid" CHECK("cold_client_installations"."steam_api_relative_path" IS NULL OR "cold_client_installations"."steam_api_relative_path" <> ''),
	CONSTRAINT "cold_client_installations_architecture_consistent" CHECK("cold_client_installations"."loader_architecture" = 'x64' OR "cold_client_installations"."steam_api_relative_path" IS NOT NULL),
	CONSTRAINT "cold_client_installations_launch_source_valid" CHECK("cold_client_installations"."launch_argument_source" IS NULL OR "cold_client_installations"."launch_argument_source" <> ''),
	CONSTRAINT "cold_client_installations_gbe_asset_id_valid" CHECK("cold_client_installations"."gbe_asset_id" > 0),
	CONSTRAINT "cold_client_installations_gse_asset_id_valid" CHECK("cold_client_installations"."gse_asset_id" > 0),
	CONSTRAINT "cold_client_installations_depot_fingerprint_valid" CHECK(length("cold_client_installations"."generated_depot_fingerprint") = 64 AND "cold_client_installations"."generated_depot_fingerprint" NOT GLOB '*[^0-9a-f]*'),
	CONSTRAINT "cold_client_installations_managed_core_files_valid" CHECK(json_valid("cold_client_installations"."managed_core_files") AND json_type("cold_client_installations"."managed_core_files") = 'array' AND json_array_length("cold_client_installations"."managed_core_files") > 0),
	CONSTRAINT "cold_client_installations_configured_at_valid" CHECK("cold_client_installations"."configured_at" >= 0)
);
